# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_TOKEN: ${{ secrets.TOKEN }}
        file_name: .env
    - name: Rsync Jbot
      uses: contention/rsync-deployments@v1.0.0
      env: 
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      with:
        args: -avzr --delete root@138.68.47.5:/opt/jbot/
    - name: Restart Jbot 
      uses: appleboy/ssh-action@master
      with:
        host: 138.68.47.5
        username: root
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          chmod +x /opt/jbot/start.sh
          /opt/jbot/start.sh
